# Generated by Django 3.2.3 on 2021-05-30 18:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Teams',
            new_name='Game',
        ),
    ]
