# Generated by Django 3.2.3 on 2021-05-30 18:36

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0002_rename_teams_game'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='logo',
            new_name='away_logo',
        ),
        migrations.AddField(
            model_name='game',
            name='home_logo',
            field=models.ImageField(default='', storage=django.core.files.storage.FileSystemStorage, upload_to=''),
        ),
    ]
