# Generated by Django 3.2.3 on 2021-07-08 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0003_auto_20210530_1236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='away_logo',
            field=models.ImageField(default='', upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='game',
            name='home_logo',
            field=models.ImageField(default='', upload_to='images/'),
        ),
    ]
