# Generated by Django 3.2.3 on 2021-07-04 00:20

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('background_img', models.ImageField(default='', storage=django.core.files.storage.FileSystemStorage, upload_to='')),
                ('background_alt', models.CharField(default='', max_length=20)),
                ('gallery_img', models.ImageField(default='', storage=django.core.files.storage.FileSystemStorage, upload_to='')),
                ('gallery_alt', models.CharField(default='', max_length=20)),
            ],
            options={
                'ordering': ['date_created'],
            },
        ),
    ]
