# Generated by Django 3.2.3 on 2021-07-08 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='images',
            name='background_img',
            field=models.ImageField(default='', upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='images',
            name='gallery_img',
            field=models.ImageField(default='', upload_to='images/'),
        ),
    ]
