# Generated by Django 3.2.3 on 2021-06-02 00:17

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PastGames',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('home_team', models.CharField(default='', max_length=30)),
                ('away_team', models.CharField(default='', max_length=30)),
                ('home_logo', models.ImageField(default='', storage=django.core.files.storage.FileSystemStorage, upload_to='')),
                ('away_logo', models.ImageField(default='', storage=django.core.files.storage.FileSystemStorage, upload_to='')),
                ('home_team_goals', models.IntegerField(default='')),
                ('away_team_goals', models.IntegerField(default='')),
            ],
            options={
                'ordering': ['date_created'],
            },
        ),
    ]
