# Generated by Django 3.2.3 on 2021-05-15 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(default='', max_length=30)),
                ('position', models.CharField(max_length=30)),
                ('player_number', models.IntegerField(default='', max_length=30)),
            ],
            options={
                'ordering': ['date_created'],
            },
        ),
    ]
