# Generated by Django 3.2.3 on 2021-05-15 23:01

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scorpion_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='photo',
            field=models.ImageField(default='', storage=django.core.files.storage.FileSystemStorage, upload_to=''),
        ),
        migrations.AlterField(
            model_name='player',
            name='player_number',
            field=models.IntegerField(default=''),
        ),
    ]
