# Generated by Django 3.2.3 on 2021-07-04 00:20

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scorpion_api', '0002_auto_20210515_1701'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='photo',
            field=models.ImageField(default='', storage=django.core.files.storage.FileSystemStorage, upload_to='images'),
        ),
    ]
