# Generated by Django 3.2.3 on 2021-07-08 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scorpion_api', '0003_alter_player_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='photo',
            field=models.ImageField(default='', upload_to='images'),
        ),
    ]
