# Generated by Django 3.2.3 on 2021-05-30 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_name', models.CharField(max_length=30)),
                ('match_played', models.IntegerField(default='')),
                ('matches_won', models.IntegerField(default='')),
                ('matches_lost', models.IntegerField(default='')),
                ('goals_scored', models.IntegerField(default='')),
                ('goals_conceded', models.IntegerField(default='')),
                ('points', models.IntegerField(default='')),
            ],
        ),
    ]
