# Generated by Django 3.2.3 on 2021-05-30 19:32

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('table', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='table',
            name='team_logo',
            field=models.ImageField(default='', storage=django.core.files.storage.FileSystemStorage, upload_to=''),
        ),
    ]
