# Generated by Django 3.2.3 on 2021-05-30 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('table', '0002_table_team_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='table',
            name='matches_drew',
            field=models.SmallIntegerField(null=True),
        ),
    ]
